Add checks for dependencies
bookman command depends of groff and ghostscript. However, the in absence
of these dependencies, no intuitive messages are shown to final users. This
commit adds checks for groff and ghostscript presence and show specific
messages to users.

diff --git a/bookman b/bookman
--- a/bookman
+++ b/bookman
@@ -85,6 +85,17 @@ do
 done
 shift $(($OPTIND - 1))
 
+# Check for dependencies
+{ echo ok | groff -ms ; } > /dev/null 2> /dev/null || {
+			printf "ERROR: You need install groff.\n" >&2
+			exit 1
+			}
+
+{ ps2pdf 2>&1 | grep Usage ; } > /dev/null 2> /dev/null || {
+			printf "ERROR: You need install ghostscript.\n" >&2
+			exit 1
+			}
+
 # Compatibility wrapper for BSD/GNU date, for parsing dates
 if date -j >/dev/null 2>&1; then
   pdate() { date -u -j -f '@%s' "$@"; }
